config/routes.rb
BoxApiLearn::Application.routes.draw do

  resource :sessions, only: %w(create new destroy)
  get '/update', to: 'sessions#update', as: :update_sessions
  resource :box_access , only: %w(index)
  get '/:folder_id', to: 'box_access#index', as: :select_folder	
  post '/save_file', to: 'box_access#save_file', as: :save_file 
 
  root to: 'box_access#index'
end

app/controllers/application_controller.rb
require 'box'
require 'awesome_print'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?

  def logged_in?
  	if (session[:token] && session[:time])
  		if Time.now >= session[:time]
			  returning = :old
  		else
        returning = :true 
      end    		
	  else
	    returning = :false
	  end
	  returning
  end

end

app/controllers/box_access_controller.rb
class BoxAccessController < ApplicationController

	
	def index

		case logged_in?
			when :true
				@box = Box::Client.new(session[:token])
			when :old
				redirect_to update_sessions_path
			else			
		end

	end

	def save_file

		@box = Box::Client.new(session[:token])
		(redirect_to :root, flash: { notice: 'No file name present, please enter a file name'} ) if params[:filename].blank?
		filename = Rails.root.join("tmp/#{params[:filename]}.txt").to_s
		File.open(filename, 'w') {|f| f.write(params[:content]) }
		file = @box.client.upload_file_by_folder_id(filename, params[:select_folder])
		ap file.inspect
		redirect_to :root, flash: { notice: "File sucessfully uploaded."}

	end
end

app/controllers/sessions_controller.rb
require 'box'
class SessionsController < ApplicationController

	def new
		@box_session = Box::Access.new
		session[:token],session[:rtoken] = @box_session.get_access_from(params['code'])
		session[:time] = (Time.now + (59*60))
		redirect_to :root

	end

	def create
		@box_session = Box::Access.new
		session[:token] = ""
		session[:rtoken] = ""
		redirect_to @box_session.get_authorize_url

	end

	def update
		@box_session = Box::Access.new(session[:token])
		session[:token],session[:rtoken] = @box_session.get_new_token(session[:rtoken])
		session[:time] = (Time.now + (59*60))
		redirect_to :root
	end

	def destroy
		session[:token] = nil
		session[:rtoken] = nil
		session[:time] = nil
		redirect_to :root
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_access_helper.rb
module BoxAccessHelper
end

app/views/application/_flash.html.erb
<% if flash[:notice] %>
	<div>
		<h3><%= flash[:notice] %><h3>
	</div>
<% end %>

app/views/application/_user_bar.html.erb
<section class='user_bar'>
<% case logged_in? %>
	<% when :true %>
		<%= link_to 'logout', sessions_path, method: :delete, class: 'button'  %>
	<% else %>
		<%= link_to 'login to box', sessions_path, method: :post, class: 'button' %>
<% end %>
</section>

app/views/box_access/_box_account.html.erb
<h2>Please write some text to save to your box account</h2>
<%= render 'flash' %>
	<%= form_tag(save_file_path, method: :post) do %>
		<%= render 'select_directory', id_value: params[:folder_id] %>
		<p> <%= label_tag 'text to save:' %> </p>
		<p> <%= text_area_tag 'content', nil, row: 5, class: 'text' %> </p>
		<p> <%= label_tag 'text_file name' %> <%= text_field_tag 'filename',nil, class: 'text_name' %> </p>
		<p> <%= submit_tag 'save file', class: 'button' %></p>
	<% end %>

app/views/box_access/_login.html.erb
<h2> Please log into box</h2> 
<p> 
	To use this app please log into box and allow access to your acount.
<p>

app/views/box_access/_select_directory.html.erb
<h2> Select Folder </h2>
<p> Please select a folder you would like to save to, click on the folder name to go into the folder. </p>
	<section class='folder'>
		<ul class='scroll'>
			<% @box.get_folder(id_value).each do |folder| %>
					<li>
					<%= link_to folder['name'], select_folder_path(folder['id']) , class: 'button' %> 
					<%= radio_button_tag 'select_folder', folder['id'] %>
					</li>
			<% end %>
		</ul>
	</section>
<%= link_to 'Back', :back , class: 'button'  %>

app/views/box_access/index.html.erb
<%= render 'user_bar' %>
<section>
	<aside class='side_bar'></aside>
	<section class='main'>
		<% if logged_in? == :false %>
			<%= render 'login' %>
		<% else %>
			<%= render 'box_account' %>
		<% end %>
	</section>
	<aside class='side_bar'></aside>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoxApiLearn</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "front_end", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%# javascript_include_tag 'http://livejs.com/live.js', "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" />
</head>
<body>
	<%= yield %>
</body>
</html>